version: '3.9'

services:
  postgres:
    container_name: lithium_backend_db
    image: postgres:${POSTGRESQL_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    ports:
      - "${POSTGRES_PORT_LOCAL}:5432"