#  liquibase only
quarkus:
  datasource:
    db-kind: postgresql 
    username: contacts
    password: contacts
    jdbc:
      url: jdbc:postgresql://localhost:5432/contacts
      max-size: 16
  liquibase:
    migrate-at-start: true